module.exports = {
	NODE_ENV: process.env.NODE_ENV,
	PORT: process.env.PORT,
	CLIENT_ADDRESS: process.env.CLIENT_ADDRESS,
	JWT_AUTH_SECRET: process.env.JWT_AUTH_SECRET,
	JWT_VERIFY_SECRET: process.env.JWT_VERIFY_SECRET,
	MAILGUN_API_KEY: process.env.MAILGUN_API_KEY,
	DISCOGS_API_KEY: process.env.DISCOGS_API_KEY,
	DISCOGS_CONSUMER_KEY: process.env.DISCOGS_CONSUMER_KEY,
	DISCOGS_CONSUMER_SECRET: process.env.DISCOGS_CONSUMER_SECRET,
};
